export const FETCH_POSTS_PENDING = 'FETCH_POSTS_PENDING'
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS'
export const FETCH_POSTS_ERROR = 'FETCH_POSTS_ERROR'

export const SORT_BY_ALPHABET = "SORT_BY_ALPHABET";
export const SORT_BY_PRICE = "SORT_BY_PRICE";
export const FILTER_BY_TITLE = "FILTER_BY_TITLE";
export const SEARCH_BY_ID = "SEARCH_BY_ID";
export const LOAD_EXACT_PAGE = "LOAD_EXACT_PAGE";
export const SORT_BY_SCORE = "SORT_BY_SCORE";
